[package]
name = "accents"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
regex = "1.10.0"
ron = "0.8.1"
serde = { version = "1.0.189", features = ["derive"] }
log = "0.4.20"
